### ISSUE TITLE
RadioService: java.lang.SecurityException: Neither user 10286 nor current process has android.permission.READ_PHONE_STATE.

### ISSUE THREAD

**Issue by TaifRaoof** [m-cakir/radio-player#5]
Hi 
this problem appear in run time and the app crash " RuntimeException "
at android.os.Parcel.readException(Parcel.java:1472)
       at android.os.Parcel.readException(Parcel.java:1426)
       at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listen(ITelephonyRegistry.java:269)

       at android.telephony.MultiSimTelephonyManager.listen(MultiSimTelephonyManager.java:184)
       at com.alforat.alforat.radio.RadioService.onCreate(RadioService.java:181)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2826)
       at android.app.ActivityThread.access$1900(ActivityThread.java:171)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)

**Comment by TaifRaoof** [comment]
Hi 
i solved this problem by adding android.permission.READ_PHONE_STATE  in manifest ...... this problem appear in android<M
