### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by TaifRaoof** [m-cakir/radio-player#6]
radio not work and this message appear 

Handler (android.os.Handler) {38681ae} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendMessage(Handler.java:519)
        at android.os.Message.sendToTarget(Message.java:416)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.prepare(ExoPlayerImplInternal.java:174)
        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:162)
        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:130)
        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:617)
        at com.example.example.radio.RadioService.play(RadioService.java:393)
        at com.example.example.radio.RadioService.playOrPause(RadioService.java:443)
        at com.example.example.radio.RadioManager.playOrPause(RadioManager.java:40)
        at com.example.example.activities.MainActivity.playTrigger_click(MainActivity.java:723)

**Comment by gonpuga** [comment]
Add instance=null;  in RadioManager.onUnbind() method.

**Comment by marcorealtime** [comment]
Thank so much. I almost lost my head loking a soluction

**Comment by harikrushn1412** [comment]
![Screen Shot 2023-02-23 at 11 20 20 AM](https://user-images.githubusercontent.com/97014601/220830130-b8cf0577-4ac2-48c5-8f0b-8322406b7d96.png)

i am facing this issue when i try to stop the radio and try to start new radio that time showing this issue and radio not starting.
 anyone having solution for this?

**Comment by harikrushn1412** [comment]
> Add instance=null; in RadioManager.onUnbind() method.

i am not able to find this method in new package.
can you help me for this point.
thank you.
